#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage $0 \"Title for your post\"" 1>&2
    exit;
fi

TITLE=${1// /-}
PSTO_FILE=_posts/`date '+%Y-%m-%d'`-$TITLE.markdown

cat >> $PSTO_FILE <<EOF
---
layout: post
title: 
category: 
tags: 
published: false
summary: 
---


EOF

echo $PSTO_FILE
open $PSTO_FILE
#vim -u _templates/vimrc $PSTO_FILE
